name: Run CheckStyle and SonarLint

on:
  push:
    paths: [ 'hello-java/**' ]
  workflow_dispatch:

jobs:
  linters:
    runs-on: ubuntu-latest
    permissions: write-all
    defaults:
      run:
        working-directory: hello-java
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run CheckStyle
        run: mvn -B checkstyle:check -Dcheckstyle.config.location=google_checks.xml
      - name: Use CheckStyle output in commit annotation
        uses: lcollins/checkstyle-github-action@v2.0.0
        with:
          path: hello-java/target/checkstyle-result.xml
# TBD - SonarLint
